import os
import platform
import glob

def PhonyTargets(env = None, **kw):
    if not env: env = DefaultEnvironment()
    for target,action in kw.items():
        env.AlwaysBuild(env.Alias(target, [], action))

env = Environment(tools=['default', 'cxxtest'])
env.Append(CPPPATH=['#src'])
env.Append(LIBPATH=['#lib'])
env.Append(LIBS='squid')
if platform.platform(True, True).find('Windows') == 0:
	env.Append(CXXTEST = os.environ['CXXTEST'])
	env.Append(CCFLAGS = '/EHsc')


env.CxxTest('string_iterator_test', source='string_iterator.t.hpp')
env.CxxTest('string_test', source='string.t.hpp')
env.CxxTest('tokens_test', source='tokens.t.hpp')
env.CxxTest('squid_lexer_test', source='squid_lexer.t.hpp')
env.CxxTest('parser_test', source='parser.t.hpp')
env.CxxTest('dot_visitor_test', source='dot_visitor.t.hpp')
