import glob
import os
import platform

parser_sources = glob.glob("../src/parser/*.cpp")
env = Environment()
if platform.platform(True, True).find('Windows') == 0:
	env.Append(CCFLAGS = '/EHsc')
env.Library('squid', parser_sources)
# if platform.platform(True, True).find('Windows') == 0:
# 	env.Append(CPPPATH=[os.environ['BOOST_DIR']])